### ISSUE TITLE
work around nsc.Settings ignoring `-D` user-set state

### ISSUE THREAD

**Issue by m50d** [random-maven/scalor-maven-plugin#11]
As discussed on issue #10 , I'd like to pass `-Dkp:genAsciiNames=true` to the compiler.

**Comment by Andrei-Pozolotin** [comment]
@m50d 
1. please verify fix in fresh 1.4.0:
https://bintray.com/random-maven/maven/scalor-maven-plugin_2.12
2. working project example for reference:
https://github.com/random-maven/scalor-maven-plugin/blob/develop/demo/pom.xml#L240
https://github.com/random-maven/scalor-maven-plugin/blob/develop/demo/pom.xml#L316
3. a way to test is:
* delete `${project.basedir}/.settings/...`
* issue from menu: `${project} -> Maven -> Update Project ...`

**Comment by m50d** [comment]
I can't find any way to confirm whether the ascii names have actually been applied in 2.12 - both scalap and the `-Xprint:kind-projector` parameter print with the parameters used in type lambdas as `?$0$` etc.. I remember previous versions of scala behaving differently but can't now reproduce. Suggest treating this as fixed? Sorry I didn't think through my use case thoroughly enough.

**Comment by Andrei-Pozolotin** [comment]
1. try to view with http://jd.benow.ca/
2. try to access expected generated member via reflection
3. post a minimal working project somewhere so I can take a look

**Comment by m50d** [comment]
I don't think the generated type names exist at all in the Java bytecode - see https://github.com/non/kind-projector#under-the-hood for the kind of code that gets generated, the type `Λ` is entirely gone at runtime. I can link a minimal project with kind-projector set up and running if you want, but I can't find any way to distinguish whether it was using ascii names or not.

**Comment by Andrei-Pozolotin** [comment]
1. the following test:

https://github.com/random-maven/scalor-maven-plugin/blob/develop/demo/src/macro/scala/meta/MacroBundle.scala#L19

https://github.com/random-maven/scalor-maven-plugin/blob/develop/demo/src/macro/scala/meta/Macro.scala#L17

https://github.com/random-maven/scalor-maven-plugin/blob/develop/demo/src/main/scala/kind/SystemProperty.scala#L11

https://github.com/random-maven/scalor-maven-plugin/blob/develop/demo/src/test/scala/kind/SystemPropertyTest.scala#L14

2. shows both in Maven and Eclipse
```
Running kind.SystemPropertyTest
property=null
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.292 sec - in kind.SystemPropertyTest
```
3. meaning that `-D` options are not propagated by compiler, 
at least in macro context, although it still may work in plugin context

4. since suggested way to alter plugin behavior is `-P`
you may want send PR to https://github.com/non/kind-projector
i.e. `-P:scalajs:sjsDefinedByDefault`
https://www.scala-js.org/doc/interoperability/sjs-defined-js-classes.html
and also use some logging to verify options activation

**Comment by Andrei-Pozolotin** [comment]
resolved https://github.com/random-maven/scalor-maven-plugin/releases/tag/1.4.0.20180329174003
